version: 2

sources:
  - name: raw
    description: "Raw tables from big query"
    database: nezzar
    schema: dbt_nezzar
    tables:
      - name: olist_closed_deals_dataset
      - name: olist_customer_dataset
        description: "Customer details"
      - name: olist_marketing_qualified_leads_dataset
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_orders_dataset
      - name: olist_product_dataset
      - name: olist_sellers_dataset
      - name: product_category_name_translation
      - name: olist_geolocation_dataset
