version: 2

sources:
  - name: raw
    description: "Raw Olist e-commerce and marketing funnel data loaded from BigQuery."
    database: n3zzar
    schema: dbt_nezzar
    tags: ["raw", "olist", "source"]

    loaded_at_field: ingestion_timestamp
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:

      - name: olist_customers_dataset
        description: "Customer details including unique customer ID and geolocation keys."
        columns:
          - name: customer_id
            description: "Primary key for customers."
            tests:
              - not_null
              - unique

      - name: olist_orders_dataset
        description: "Orders placed on the marketplace with full lifecycle timestamps."
        columns:
          - name: order_id
            description: "Primary key for orders."
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Foreign key to customers."
            tests:
              - not_null
              - relationships:
                  to: ref('stg_olist_customers')
                  field: customer_id
          - name: order_status
            description: "Order status (approved, delivered, shipped, canceled, etc.)."
            tests:
              - accepted_values:
                  values: ["approved","delivered","unavailable","invoiced","processing","shipped","created","canceled"]

      - name: olist_order_items_dataset
        description: "Items contained within each order, including product, seller, and freight cost."
        columns:
          - name: order_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: seller_id
            tests:
              - not_null
          - name: order_item_id
            description: "Line number of the item in the order."

      - name: olist_order_payments_dataset
        description: "Payments for each order, including payment method, value, and installments."

      - name: olist_products_dataset
        description: "Product catalog including physical characteristics and product category."
        columns:
          - name: product_id
            tests:
              - not_null
              - unique

      - name: olist_sellers_dataset
        description: "Seller information including unique seller ID and location fields."
        columns:
          - name: seller_id
            tests:
              - not_null
              - unique

      - name: olist_geolocation_dataset
        description: "Mapping of postal codes to latitude/longitude geolocation points."

      - name: product_category_name_translation
        description: "Mapping of Portuguese product category names to English."
        Test:
          - relationships:
              to: ref('stg_products')
              field: product_category_name

      - name: olist_marketing_qualified_leads_dataset
        description: "Marketing Qualified Leads (MQLs) representing potential sellers."
        columns:
          - name: mql_id
            tests:
              - unique
              - not_null

      - name: olist_closed_deals_dataset
        description: "Deals closed from MQLs, linking to sellers and marking conversion."
        columns:
          - name: seller_id
            tests:
              - not_null
              - relationships:
                  to: ref('stg_olist_sellers')
                  field: seller_id
